# Hugolify content available https://github.com/Hugolify/hugolify-template/wiki/Content-sections

imports:

# Core theme
- path: github.com/hugolify/hugolify-theme

# CMS
- path: github.com/hugolify/hugolify-decap-cms
