_merge: deep
animation: false
posts:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "500x375"
    mobile: "300x225"
    scrollsnap: "240x180"
services:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "500x200"
    mobile: "300x120"
    scrollsnap: "240x96"